#POST http://localhost:8080/patients

POST http://localhost:8084/api/patients
Content-Type: application/json

{
    "name": "Marsal.dev23.test",
    "email": "marsal.dev23.test@example.com",
    "address": "123 main street",
    "dateOfBirth": "1999-03-09",
    "registrationDate": "2023-10-10"
}